spring.application.name=forohub

spring.datasource.url=jdbc:mysql://localhost:3306/forohub_db
spring.datasource.username=root
spring.datasource.password=Germa663d2y
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
